name: Feature Request
description: Suggest an idea
labels: ['enhancement']
title: 'Feature: '
body:
  - type: markdown
    attributes:
      value: Before getting started, please checked the [GitHub Issues](https://github.com/lin-stephanie/rehype-callouts/issues) (open or closed) and there are no similar issues.
  - type: textarea
    validations:
      required: true
    attributes:
      label: Goal or desired outcome
      description: Before describing your requested feature, please describe more generally the problem, pain-point, or use case you'd like to solve for.
  - type: textarea
    validations:
      required: true
    attributes:
      label: Feature description
      description: Please describe the desired feature in as much detail as you are able.
  - type: textarea
    attributes:
      label: Additional context
      description: If applicable, add any other context or screenshots to help explain the request.
